brew 'zsh'
brew 'git'
brew 'git-delta'
# brew 'gibo'
brew 'ripgrep'
brew 'axel'
brew 'bat'
brew 'tealdeer'
brew 'bottom'
brew 'dust'
brew 'duf'
brew 'tree'
brew 'procs'
brew 'curlie'
brew 'dog'
brew 'gping'
brew 'xh'
brew 'hexyl'
brew 'coreutils'
# brew 'grep'
brew 'findutils'
brew 'sqlite'
brew 'python3'
# brew 'bchunk'
cask 'iina'
cask 'forklift'
cask 'sublime-text'
cask 'sublime-merge'
cask 'openemu'

tap 'patthemav/custom'
brew 'vim-custom', args: ["with-gettext"]
